// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "DLAnimationMacros.h"

namespace EAnimationTag
{
	/*角色动画状态*/
	namespace ECharacterAnimState
	{
		/*空闲状态*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);
		/*在陆地*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InTheLand);
		/*正在空中*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(InTheSky);
		/*锁定目标的状态*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockTarget);
		/*跑*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Run);
		/*冲刺( 加速跑 )*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint);
		/*走*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walk);
		/*转向*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(TurnTo);
		/*翻滚*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Roll);
	}

	namespace EBoneName
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(IK_Hand_Root);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ik_hand_r);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ik_hand_l);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(IK_Foot_Root);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ik_foot_r);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ik_foot_l);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bip001);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pelvis);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spine);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spine1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spine2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Neck);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Head);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Clavicle);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_UpperArm);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Forearm);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Hand);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger0);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger02);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger11);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger12);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger21);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger22);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger3);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger31);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger32);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger4);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger41);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger42);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_ForeTwist);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_ForeTwist1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LUpArmTwist);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LUpArmTwist1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Clavicle);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_UpperArm);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Forearm);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Hand);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger0);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger02);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger11);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger12);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger21);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger22);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger3);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger31);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger32);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger4);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger41);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger42);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_ForeTwist);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_ForeTwist1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(RUpArmTwist);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(RUpArmTwist1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Breast_L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Breast_R);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Thigh);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Calf);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Foot);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Toe0);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkinMend_Calf_R01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkinMend_Knee_L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Thigh);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Calf);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Foot);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Toe0);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkinMend_Calf_L01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkinMend_Knee_R);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stretch_Pelvis_R);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stretch_Pelvis_L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(VB_FootTarget_L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(VB_FootTarget_R);
	}
}