#pragma once

#include "CoreMinimal.h"
#include "Animation/DLAnimMacros.h"
#include "AnimationV2/DLAnimationMacros.h"

namespace EAnimTagDef
{
	inline FName TagBuild(FString Scope, const FString& Tag)
	{
		Scope.AppendChar('.').Append(Tag);
		return FName(Scope);
	}

	/*角色动画状态*/
	namespace ECharacterAnimState
	{
		/*待机*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);
		/*行走(方向)*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(WalkDirection);
		/*行走（转身）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walk_Turn);
		/*行走(停止)*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walk_Stop);
		/*锁定行走(方向)*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locked_Walk_Direction);
		/*小跑（方向）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jog_Direction);
		/*小跑（转身）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jog_Turn);
		/*小跑（停止）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jog_Stop);
		/*锁定小跑(方向)*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Locked_Jog_Direction);
		/*加速（方向）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Accelerate);
		/*疾跑（方向）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint_Direction);
		/*疾跑（转身）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint_Turn);
		/*疾跑（停止）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint_Stop);
		/*翻滚（方向）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Roll_Direction);
		/*翻滚后（转身）*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(After_Roll_Then_Turn);
		/*后撤*/
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Retreat);
	}

	//动画名字
	namespace EAnimName
	{
		// DECLARE_ANIM_TAG(AnimName, Idle);
		// DECLARE_ANIM_TAG(AnimName, Death);
		// DECLARE_ANIM_TAG(AnimName, BattleIdle);
		// DECLARE_ANIM_TAG(AnimName, WalkDirectionForward);
		// DECLARE_ANIM_TAG(AnimName, WalkDirectionRight);
		// DECLARE_ANIM_TAG(AnimName, WalkDirectionLeft);
		// DECLARE_ANIM_TAG(AnimName, WalkDirectionBackward);
		// DECLARE_ANIM_TAG(AnimName, WalkTurnRight);
		// DECLARE_ANIM_TAG(AnimName, WalkTurnLeft);
	}

	namespace EBoneName
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Root);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(IK_Hand_Root);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ik_hand_r);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ik_hand_l);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(IK_Foot_Root);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ik_foot_r);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ik_foot_l);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bip001);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Pelvis);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spine);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spine1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Spine2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Neck);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Head);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Clavicle);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_UpperArm);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Forearm);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Hand);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger0);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger02);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger11);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger12);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger21);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger22);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger3);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger31);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger32);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger4);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger41);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Finger42);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_ForeTwist);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_ForeTwist1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LUpArmTwist);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(LUpArmTwist1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Clavicle);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_UpperArm);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Forearm);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Hand);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger0);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger02);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger11);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger12);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger2);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger21);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger22);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger3);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger31);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger32);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger4);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger41);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Finger42);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_ForeTwist);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_ForeTwist1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(RUpArmTwist);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(RUpArmTwist1);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Breast_L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Breast_R);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Thigh);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Calf);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Foot);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(L_Toe0);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkinMend_Calf_R01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkinMend_Knee_L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Thigh);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Calf);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Foot);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(R_Toe0);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkinMend_Calf_L01);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkinMend_Knee_R);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stretch_Pelvis_R);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stretch_Pelvis_L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(VB_FootTarget_L);
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(VB_FootTarget_R);
	}
}